apiVersion: v1
kind: Service
metadata:
  name: factorial-service-load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    name: factorial-mn